///////////////////////////////////////////////////////////
//  IProtocol.cs
//  Implementation of the Interface IProtocol
//  Generated by Enterprise Architect
//  Created on:      26-sep-2015 19:47:55
//  Original author: benla
///////////////////////////////////////////////////////////

namespace Backend.OpretProdukt
{
    public interface IProtocol  {

        string GetCmdString(IProduct product);
    }
}//end IProtocol