///////////////////////////////////////////////////////////
//  ManagerFactory.cs
//  Implementation of the Class ManagerFactory
//  Generated by Enterprise Architect
//  Created on:      26-sep-2015 20:44:30
//  Original author: benla
///////////////////////////////////////////////////////////

namespace Backend.OpretProdukt
{
    public class ManagerFactory {

        public ProductManager MakeProductManager(string type){

            switch (type)
            {
                case "Project":
                    return new PrjProductManager();
                default:
                    return null;

            }
        }

    }
}//end ManagerFactory