///////////////////////////////////////////////////////////
//  PrjProtocol.cs
//  Implementation of the Class PrjProtocol
//  Generated by Enterprise Architect
//  Created on:      26-sep-2015 19:47:55
//  Original author: benla
///////////////////////////////////////////////////////////

using System;
using SharedLib.Models;
using SharedLib.Protocol;
using SharedLib.Protocol.CmdMarshallers;
using SharedLib.Protocol.Commands;

namespace Backend.OpretProdukt
{
    public class PrjProtocol : IProtocol {

        public string GetCmdString(IProduct product)
        {

            var cmd = new CreateProductCmd((Product)product);
            XmlMarshal marshal = new XmlMarshal();
            CreateProductMarshal cmarshal = new CreateProductMarshal();
            return cmarshal.Encode(cmd);
        }

    }
}//end PrjProtocol