///////////////////////////////////////////////////////////
//  ProductManager.cs
//  Implementation of the Class ProductManager
//  Generated by Enterprise Architect
//  Created on:      26-sep-2015 19:47:55
//  Original author: benla
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace Backend.OpretProdukt
{
    public abstract class ProductManager
    {
        abstract public IProduct myProduct { get; set; }
        abstract public IProtocol myProtocol { get; set; }

        public abstract bool AddProduct(Dictionary<string, string> propDictionary);

        protected abstract string EncodeProduct();

        protected abstract IProduct MakeProduct(Dictionary<string, string> propDictionary);

        protected abstract IProtocol MakeProtocol();
    }
} //end ProductManager