///////////////////////////////////////////////////////////
//  IProtocol.cs
//  Implementation of the Interface IProtocol
//  Generated by Enterprise Architect
//  Created on:      28-sep-2015 17:43:51
//  Original author: benja
///////////////////////////////////////////////////////////

using Backend.Models;
using SharedLib.Models;

namespace Backend.Brains
{
    public interface IProtocol
    {
        string ProductXMLParser(Product toParse);
        string CategoryXMLParser(BackendProductCategory toParse);
        string EditProductXMLParser(BackendProduct toParse);
        string EditCategoryXMLParser(BackendProductCategory toParse);
        string DeleteCategoryXMLParser(BackendProductCategory toParse);
        string DeleteProductXMLParser(BackendProduct toParse);
        string GetCatalougXMLParser();
    } //end IProtocol
}