///////////////////////////////////////////////////////////
//  PrjProtokol.cs
//  Implementation of the Class PrjProtokol
//  Generated by Enterprise Architect
//  Created on:      28-sep-2015 17:43:51
//  Original author: benja
///////////////////////////////////////////////////////////

using SharedLib.Models;
using SharedLib.Protocol;
using SharedLib.Protocol.Commands;

namespace Backend.Brains
{
    public class PrjProtokol : IProtocol
    {
        public string ProductXMLParser(Product toParse)
        {
            var createProductCmd = new CreateProductCmd(toParse);
            var protocol = new Protocol();

            return protocol.Encode(createProductCmd);
        }
    } //end PrjProtokol
}