///////////////////////////////////////////////////////////
//  AddProductCB.cs
//  Implementation of the Class AddProductCB
//  Generated by Enterprise Architect
//  Created on:      28-sep-2015 17:43:46
//  Original author: benja
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using System.IO;
using SharedLib.Models;
using Backend.Communication;

namespace Backend.AddProduct {
    public class AddProductCB : IAddProduct
    {
        readonly IProtocol _protocol;
        string _error;

        public IProductGenerator ProductGenerator;
        private IClient _client;



        public AddProductCB(IProtocol protocol, IClient client)
        {
            _protocol = protocol;
            LastError = null;
            ProductGenerator = new ProductGenerator();
            _client = client;

        }

        public bool CreateProduct(Dictionary<string, string> data)
        {

            // Create the product
            var product = ProductGenerator.GenerateProduct(data);
            

            if (product.Name == "" || product.Price < 0 || product.ProductNumber == "")
            {
                LastError = "Enter correct product details.";
                Error.StdErr(LastError);
                return false;
            }

         

            // Generate XML from product
            string cmdtoSend = _protocol.ProductXMLParser(product);

            // New client to use to send data to central server
            


            // Send the XML data
            if (!_client.Send(cmdtoSend))
            {
                LastError = "Connection Error";
                Error.StdErr(LastError);
                return false;
            }
            return true;

        }

        public string LastError
        {
            private set { _error = value; }
            get { return _error; }
        }

    }//end AddProductCB
}