///////////////////////////////////////////////////////////
//  IAddProduct.cs
//  Implementation of the Interface IAddProduct
//  Generated by Enterprise Architect
//  Created on:      28-sep-2015 17:43:51
//  Original author: benja
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace Backend.AddProduct
{
    public interface IAddProduct
    {
        string LastError { get; }
        bool CreateProduct(Dictionary<string, string> data);
    } //end IAddProduct
}