///////////////////////////////////////////////////////////
//  AddProductCB.cs
//  Implementation of the Class AddProductCB
//  Generated by Enterprise Architect
//  Created on:      28-sep-2015 17:43:46
//  Original author: benja
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using SharedLib.Models;
using Backend.Communication;

namespace Backend.AddProduct {
    public class AddProductCB : IAddProduct {
        IProtocol _protocol;
        AddProductWindow _window;
        string _error;

        private string ip = "127.0.0.1";
        private int port = 9000;

        public AddProductCB(IProtocol protocol, AddProductWindow window) {
            _protocol = protocol;
            _window = window;
            LastError = null;
        }


        public bool CreateProduct() {

            // Create the product
            var product = GenerateProduct();

            if (product == null)
            {
                return false;
            }

            // Generate XML from product
            string cmdtoSend = _protocol.ProductXMLParser(product);

            // New client to use to send data to central server
            var client = new Client(ip, port);

            // Send the XML data
            client.Send(cmdtoSend);

            return true;
        }

        private Product GenerateProduct()
        {
            var product = new Product();
            product.Name = _window.textboxName.Text;
            product.ProductNumber = _window.textboxBarcode.Text;

            // Convert textboxPrice to decimal number
            try
            {
                product.Price = decimal.Parse(_window.textboxPrice.Text);
            }
            catch (Exception e)
            {
                LastError = "Error converting price to number";
                return null;
            }

            return product;
        }

        public string LastError
        {
            private set { _error = value; }
            get { return _error; }
        }

    }//end AddProductCB
}