///////////////////////////////////////////////////////////
//  AddProductCB.cs
//  Implementation of the Class AddProductCB
//  Generated by Enterprise Architect
//  Created on:      28-sep-2015 17:43:46
//  Original author: benja
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using SharedLib.Models;

namespace Backend.AddProduct {
    public class AddProductCB : IAddProduct {
        IProtocol _protocol;
        AddProductWindow _window;
        string _error;

        public AddProductCB(IProtocol protocol, AddProductWindow window) {
            _protocol = protocol;
            _window = window;
            LastError = null;
        }


        public bool CreateProduct() {

            var product = new Product();
            product.Name = _window.textboxName.Text;
            product.ProductNumber = _window.textboxBarcode.Text;

            // Convert textboxPrice to decimal number
            try {
                product.Price = decimal.Parse(_window.textboxPrice.Text);
            }
            catch (Exception e)
            {
                LastError = "Error converting price to number";
            }

            string cmdtoSend = _protocol.ProductXMLParser(product);

            /* SOME SHIT ON SERVER */

            return true;
        }

        public string LastError
        {
            private set { _error = value; }
            get { return _error; }
        }

    }//end AddProductCB
}