///////////////////////////////////////////////////////////
//  PrjProtokol.cs
//  Implementation of the Class PrjProtokol
//  Generated by Enterprise Architect
//  Created on:      28-sep-2015 17:43:51
//  Original author: benja
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using SharedLib.Protocol;
using SharedLib.Models;



public class PrjProtokol : IProtocol {

	/// 
	/// <param name="toParse"></param>
	public string ProductXMLParser(Product toParse){

        // something that returns a string;
        return " ";
	}

}//end PrjProtokol