///////////////////////////////////////////////////////////
//  PrjProtokol.cs
//  Implementation of the Class PrjProtokol
//  Generated by Enterprise Architect
//  Created on:      28-sep-2015 17:43:51
//  Original author: benja
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using SharedLib.Models;
using SharedLib.Protocol.Commands;
using SharedLib.Protocol;

namespace Backend.AddProduct
{
    public class PrjProtokol : IProtocol
    {
        public string ProductXMLParser(Product toParse)
        {
            var createProductCmd = new CreateProductCmd(toParse);
            var protocol = new Protocol();

            return protocol.Encode(createProductCmd);
        }

    }//end PrjProtokol
}