///////////////////////////////////////////////////////////
//  AddProductCB.cs
//  Implementation of the Class AddProductCB
//  Generated by Enterprise Architect
//  Created on:      28-sep-2015 17:43:46
//  Original author: benja
///////////////////////////////////////////////////////////

using Backend.AddProduct.Models;
using Backend.Communication;

namespace Backend.AddProduct.Brains
{
    public class AddProductCB : IAddProduct
    {
        private readonly IClient _client;
        private readonly IProtocol _protocol;
        public  IError Error;


        public AddProductCB(IProtocol protocol, IClient client)
        {
            _protocol = protocol;
            LastError = null;
            _client = client;
            Error = new Error();
        }

        public bool CreateProduct(BackendProduct Product)
        {
            // Create the product
            var product = Product;


            if (product.BName == "" || product.BPrice < 0 || product.BProductNumber == "")
            {
                LastError = "Enter correct product details.";
                Error.StdErr(LastError);
                return false;
            }


            // Generate XML from product
            var cmdtoSend = _protocol.ProductXMLParser(product);


            // Send the XML data
            if (!_client.Send(cmdtoSend))
            {
                LastError = "Connection Error";
                Error.StdErr(LastError);
                return false;
            }
            return true;
        }

        public string LastError { private set; get; }
    } //end AddProductCB
}